[package]
name = "fetch_data_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.140"
base64 = "0.21"
sha2 = "0.10.9"
serde = { version = "1.0", features = ["derive"] }
num-bigint = "0.4.6"
num-traits = "0.2.19"
anyhow = "1.0.98"
pod2 = { git="https://github.com/0xPARC/pod2", branch = "feat/sync-send", features = ["time"]}
plonky2 = { git = "https://github.com/0xPolygonZero/plonky2"}
ssh-key = "0.6.7"
